plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
	id("cz.habarta.typescript-generator") version "3.2.1263"
}

group = 'com.konfyrm'
version = '0.0.1-SNAPSHOT'
description = 'Useful tool for exam training :)'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'software.amazon.awssdk:s3:2.26.0'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
	implementation 'org.apache.pdfbox:pdfbox:3.0.2'
	implementation 'com.google.guava:guava:33.0.0-jre'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
}

tasks.named('test') {
	useJUnitPlatform()
}

// === TypeScript generation tasks ===
generateTypeScript {
	jsonLibrary = 'jackson2'
	classPatterns = [
			'**.domain.dto.**'
	]
	excludeClassPatterns = [
	        '**.soundcloud.domain.dto.**',
			'**Builder**'
	]
	outputKind = 'module'
	outputFile = '../gigatester-ui/src/app/models/models.d.ts'
	mapEnum = 'asEnum'
}

tasks.register("generateApiUrls", cz.habarta.typescript.generator.gradle.GenerateTask) {
	jsonLibrary = 'jackson2'
	classPatterns = [
			'**.domain.urls.client.**'
	]
	excludeClassPatterns = [
			'**.soundcloud.domain.dto.**'
	]
	outputFile = '../gigatester-ui/src/app/models/api-urls.ts'
	outputKind = 'module'
	outputFileType = 'implementationFile'
	mapEnum = 'asEnum'
}

tasks.register("generateApiUrlParams", cz.habarta.typescript.generator.gradle.GenerateTask) {
	jsonLibrary = 'jackson2'
	classPatterns = [
			'**.domain.params.client.**'
	]
	excludeClassPatterns = [
			'**.soundcloud.domain.dto.**'
	]
	outputFile = '../gigatester-ui/src/app/models/api-url-params.ts'
	outputKind = 'module'
	outputFileType = 'implementationFile'
	mapEnum = 'asEnum'
}