spring:
  application:
    name: gigatester

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gigatester
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloudflare:
  r2:
    endpoint: <endpoint>
    access-key: <access-key>
    secret-key: <secret-key>
    bucket: gigatester-images-dev
    public-url: <public-url>